name: Blackbox-Auth CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  AZURE_CONTAINER_REGISTRY: blackboxhub
  CONTAINER_APP_NAME: blackbox.auth
  RESOURCE_GROUP: "Container"
  
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/BlackBox.Auth
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
     
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Docker Image Build And Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}
        file: ./src/BlackBox.Auth/Dockerfile
        context: .
      # run: |
      #   docker buildx build \
      #   -f ./src/BlackBox.Auth/Dockerfile . \
      #   --push \
      #   --tag ${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest
  
