name: Blackbox-Auth CI

on:
  push:
    branches: [ "main" ]
    paths:
      - /src/BlackBox.Auth
  pull_request:
    branches: [ "main" ]
    paths:
      - /src/BlackBox.Auth
env:
  IMAGE_NAME: "BlackBox-Auth"
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Restore Nuget
        run: dotnet restore
      - name: Build .Net
        run: dotnet build
      - name: Publish .Net
        run: dotnet publish
  Docker-Build-Push: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest

      
      
