name: Blackbox-Auth CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CONTAINER_APP_NAME: blackbox.auth
  RESOURCE_GROUP: Container
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/BlackBox.Auth/BlackBox.Auth.csproj
    - name: Build
      run: dotnet build src/BlackBox.Auth/BlackBox.Auth.csproj -c Release
    - name: Publish
      run: dotnet publish src/BlackBox.Auth/BlackBox.Auth.csproj
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
     
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # - name: Build and push container image to ACR
    #   run: |
    #     ls -la
    #     # build and push
    #     docker buildx build \
    #     -f src/BlackBox.Auth/Dockerfile . \
    #     --push \
    #     -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
        file: src/BlackBox.Auth/Dockerfile
        context: .

