name: Blackbox-Auth CI

on:
  
  push:
    branches: [ "main" ]
    paths:
      - "src/BlackBox.Auth"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/BlackBox.Auth"
  workflow_dispatch:
env:
  IMAGE_NAME: "blackboxauth"
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/BlackBox.Auth
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
      
  Docker-Build-Push: 
    runs-on: ubuntu-latest
    steps:
      # Setp 1: Checkout the repository
      - uses: actions/checkout@v4
        
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       
      # Step 3: Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build docker image and push
      - name: Docker Image Build And Push
        run: |
          docker buildx build \
          -f ./src/BlackBox.Auth/Dockerfile . \
          --push \
          --tag ${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest

      
      
