name: Blackbox-Auth CI

on:
  
  push:
    branches: [ "main" ]
    paths:
      - /src/BlackBox.Auth
  pull_request:
    branches: [ "main" ]
    paths:
      - /src/BlackBox.Auth
  workflow_dispatch:
env:
  IMAGE_NAME: "BlackBox-Auth"
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/BlackBox.Auth
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
      
  Docker-Build-Push: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/BlackBox.Auth
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blackboxauth:latest

      
      
